# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/python-wrapper"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    cooldown:
      default-day: 3
      enabled: true
    groups:
      python-patch-and-minor:
        update-types:
          - "patch"
          - "minor"
      python-major:
        update-types:
          - "major"
  - package-ecosystem: "npm"
    directory: "/js-applet"
    schedule:
      interval: "weekly"
    cooldown:
      default-day: 3
      enabled: true
    groups:
      js-patch-and-minor:
        update-types:
          - "patch"
          - "minor"
      js-major:
        update-types:
          - "major"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-day: 3
      enabled: true
    groups:
      github-actions-patch-and-minor:
        update-types:
          - "patch"
          - "minor"
      github-actions-major:
        update-types:
          - "major"
