= Installation

To install the latest version of the library, run:

[source, console]
----
pip install neo4j-viz
----

== Optional dependencies

In addition, there are a few optional dependencies that you can install to enable additional features of the library.

=== Pandas DataFrames `from_dfs` importer

To install the additional dependencies required for the link:{api-uri}/from_pandas[`from_dfs`] importer you can run:

[source, console]
----
pip install neo4j-viz[pandas]
----

=== Neo4j `from_neo4j` importer

To install the additional dependencies required for the link:{api-uri}/from_neo4j[`from_neo4j`] importer you can run:

[source, console]
----
pip install neo4j-viz[neo4j]
----

=== Neo4j Graph Data Science `from_gds` importer

To install the additional dependencies required for the link:{api-uri}/from_gds[`from_gds`] importer you can run:

[source, console]
----
pip install neo4j-viz[gds]
----

=== Neo4j Graph Data Science `from_snowflake` importer

To install the additional dependencies required for the link:{api-uri}/from_snowflake[`from_snowflake`] importer you can run:

[source, console]
----
pip install neo4j-viz[snowflake]
----

=== Notebook tutorials

To install all the additional dependencies required for the link:{tutorials-uri}[notebook examples] you can run:

[source, console]
----
pip install neo4j-viz[notebook]
----