= Rendering a graph

In this section, we will discuss how to render a link:{api-docs-uri}/visualization-graph[`VisualizationGraph` object]
to display the graph visualization.

If you have not yet created a `VisualizationGraph` object, refer to one of the following sections:

* xref:getting-started.adoc[Getting started] for creating a visualization graph from scratch using `neo4j-viz`
  primitives like link:{api-docs-uri}/node[Node] and link:{api-docs-uri}/relationship[Relationship] and
  link:{api-docs-uri}/visualization-graph[`VisualizationGraph`] directly.
* xref:integration/index.adoc[] for importing data from a Pandas DataFrame or Neo4j GDS projection.

== The `render` method

Once you have a `VisualizationGraph` object, you can render it using the `render` method.
This will return a HTML object that will be displayed in an environment that supports HTML rendering, such as
Jupyter notebooks or streamlit application.

All parameter of the `render` method are optional, and the full list of parameters of them is listed in the API
reference: link:{api-docs-uri}/visualization-graph/#neo4j_viz.VisualizationGraph.render[neo4j_viz.VisualizationGraph.render()].

The most important parameters to be aware of are the `width` and `height` parameters, which control the size of
HTML object that will be rendered.
You can provide these either as a percentage of the available space (eg. `"80%"`), or as an absolute pixel value
(eg. `"800px"`).

Further you can change the layout of the graph using the `layout` parameter, which can be set to one of the following values:

* `Layout.FORCE_DIRECTED` - Nodes are arranged using the Force-Directed algorithm, which simulates physical forces.
To customize the layout, use _ForceDirectedOptions_ via _layout_options_.
* `Layout.HIERARCHICAL` - Arranges nodes by the directionality of their relationships, creating a tree-like structure.
To customize the layout use _HierarchicalLayoutOptions_ via _layout_options_.
* `Layout.COORDINATE` - Arranges nodes based on coordinates defined in _x_ and _y_ properties on each node.

Another thing of note is the `max_allowed_nodes` parameter, which controls the maximum number of nodes that is allowed
for the graph to contain in order to be rendered.
It defaults to 10.000, because rendering a large number of nodes can be slow and unresponsive.
However, you can increase this value if you are confident that your environment can handle the scale.
In this case you might also want to pass `Renderer.WEB_GL` as the `renderer` to improve performance.

Relationships whose `source` or `target` is not part of the graph's nodes ("dangling" relationships) cannot be
drawn, and a graph containing them may appear empty.
By default `render` emits a warning that lists the offending relationships so the problem is not silent.
You can change this with the `on_dangling` parameter: pass `"error"` to raise a `ValueError` instead, or `"none"`
to skip the check entirely.

By default a tooltip showing IDs and properties will be shown when mouse hovering over a node or relationship.
But you can disable this by passing `show_hover_tooltip=False`.

=== Examples

Refer to the xref:getting-started.adoc[] and the link:{tutorials-docs-uri}[tutorials] for
examples of `render` method usage.

== Using with Streamlit

There are two ways to display a graph in a https://streamlit.io/[Streamlit] app.

=== Static rendering

The HTML object returned by `render` can be embedded directly. Pass its `data`
attribute to `st.iframe`:

[source, python]
----
import streamlit as st
from neo4j_viz import VisualizationGraph

st.iframe(VG.render(height="600px").data, height=600)
----

This is the simplest option and fully supports the in-canvas interactions
(pan, zoom, selection, layout switching), but nothing is communicated back to
Python.

=== Interactive widget with two-way sync

To read interactions such as the current selection back in Python, use
`neo4j_viz.streamlit.display_widget`. It renders the same interactive widget as
`render_widget` does in a notebook and syncs the `selected` and `options` state
back into the `GraphWidget` you pass in (in place) on each rerun.

This requires the `streamlit` optional dependency (Streamlit 1.58 or newer):

[source, bash]
----
pip install neo4j-viz[streamlit]
----

[source, python]
----
import streamlit as st
from neo4j_viz.streamlit import display_widget

widget = VG.render_widget()
display_widget(widget, key="my-graph")

selection = widget.selected
st.write("Selected node IDs:", selection.nodeIds)
----

`display_widget` takes a `GraphWidget` (as returned by
`VisualizationGraph.render_widget()`), so you can configure the widget with all
the usual options (`layout`, `initial_zoom`, `height`, ...) when building it.
When displaying more than one graph in an app, give each a unique `key`.

== Exporting to HTML

The object returned by the `render` method is a `IPython.display.HTML` object.
In addition to being displayed in a Jupyter notebook or streamlit application, it can also be saved as an HTML file.
This could be useful if you want to share the visualization with others or embed it in a web page.

To save the HTML data to a file, you can use the `data` attribute of the HTML object:

[source, python]
----
html = VG.render(...)

with open("my_graph.html", "w") as f:
    f.write(html.data)
----
