import type { AnyModel } from "@anywidget/types";
import widget, { type WidgetData } from "./graph-widget";

/**
 * Standalone entrypoint for static HTML rendering (non-Jupyter).
 * Data is injected by Python via window.__NEO4J_VIZ_DATA__.
 */

declare global {
  interface Window {
    __NEO4J_VIZ_DATA__?: Partial<WidgetData>;
  }
}

const data = window.__NEO4J_VIZ_DATA__;

if (!data) {
  document.body.innerHTML = `
    <div style="padding: 2rem; font-family: system-ui, sans-serif;">
      <h1>Missing visualization data</h1>
      <p>Expected <code>window.__NEO4J_VIZ_DATA__</code> to be set.</p>
      <p>This page should be generated by <code>neo4j_viz</code>'s <code>render()</code> method.</p>
    </div>
  `;
  throw new Error("window.__NEO4J_VIZ_DATA__ is not defined");
}

/**
 * Read-only model shim for static HTML rendering.
 * Mutations (set/save_changes) are no-ops since there's no kernel to sync with.
 */
const model: Pick<
  AnyModel<WidgetData>,
  "get" | "on" | "off" | "set" | "save_changes"
> = {
  get<K extends keyof WidgetData>(key: K): WidgetData[K] {
    return data[key] as WidgetData[K];
  },
  on() {},
  off() {},
  set() {},
  save_changes() {},
};

const el = document.getElementById("neo4j-viz-container");
if (!el) {
  throw new Error("Container element #neo4j-viz-container not found");
}

el.style.width = data.width ?? "100%";
el.style.height = data.height ?? "100vh";

widget.render({ model, el } as Parameters<typeof widget.render>[0]);
