import widget, { type WidgetData } from "./graph-widget";
import { createLocalModel } from "./local-model";

/**
 * Standalone entrypoint for static HTML rendering (non-Jupyter).
 * Data is injected by Python as an inert <script type="application/json"
 * id="neo4j-viz-data"> block; we read it back with JSON.parse, which treats
 * every key (including __proto__) as ordinary data rather than executable.
 */

const dataEl = document.getElementById("neo4j-viz-data");
const data: Partial<WidgetData> | undefined = dataEl?.textContent
  ? JSON.parse(dataEl.textContent)
  : undefined;

if (!data) {
  document.body.innerHTML = `
    <div style="padding: 2rem; font-family: system-ui, sans-serif;">
      <h1>Missing visualization data</h1>
      <p>Expected a <code>&lt;script type="application/json" id="neo4j-viz-data"&gt;</code> data block.</p>
      <p>This page should be generated by <code>neo4j_viz</code>'s <code>render()</code> method.</p>
    </div>
  `;
  throw new Error("neo4j-viz data block not found");
}

// Kernel-less model for the static HTML page: `set` updates local state and
// notifies listeners so controlled props (e.g. `selected`) stay interactive;
// nothing is synced back to Python. See createLocalModel for details.
const model = createLocalModel<WidgetData>(data);

const el = document.getElementById("neo4j-viz-container");
if (!el) {
  throw new Error("Container element #neo4j-viz-container not found");
}

el.style.width = data.width ?? "100%";
el.style.height = data.height ?? "100vh";

widget.render({ model, el } as Parameters<typeof widget.render>[0]);
