import widget, { type WidgetData } from "./graph-widget";
import { createLocalModel } from "./local-model";

/**
 * Standalone entrypoint for static HTML rendering (non-Jupyter).
 * Data is injected by Python via window.__NEO4J_VIZ_DATA__.
 */

declare global {
  interface Window {
    __NEO4J_VIZ_DATA__?: Partial<WidgetData>;
  }
}

const data = window.__NEO4J_VIZ_DATA__;

if (!data) {
  document.body.innerHTML = `
    <div style="padding: 2rem; font-family: system-ui, sans-serif;">
      <h1>Missing visualization data</h1>
      <p>Expected <code>window.__NEO4J_VIZ_DATA__</code> to be set.</p>
      <p>This page should be generated by <code>neo4j_viz</code>'s <code>render()</code> method.</p>
    </div>
  `;
  throw new Error("window.__NEO4J_VIZ_DATA__ is not defined");
}

// Kernel-less model for the static HTML page: `set` updates local state and
// notifies listeners so controlled props (e.g. `selected`) stay interactive;
// nothing is synced back to Python. See createLocalModel for details.
const model = createLocalModel<WidgetData>(data);

const el = document.getElementById("neo4j-viz-container");
if (!el) {
  throw new Error("Container element #neo4j-viz-container not found");
}

el.style.width = data.width ?? "100%";
el.style.height = data.height ?? "100vh";

widget.render({ model, el } as Parameters<typeof widget.render>[0]);
