name: Build JS Applet and check for changes
# This workflow builds the nvl_entrypoint and checks for changes in the neo4j_viz resources

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "js-applet/src/nvl_entrypoint/**" # JS sources
      - "js-applet/webpack.config.js"
      - "js-applet/babel.config.js"
      - "js-applet/package.json"
      - "js-applet/tsconfig.json"
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  tests:

    # The type of runner that the job will run on
    runs-on: "ubuntu-latest"

    defaults:
      run:
        working-directory: js-applet

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '23.x'
      - name: Setup
        run: yarn
      - name: Build
        run: yarn build
      - name: Check for changes (run `yarn build` locally + commit if this fails)
        run: git diff --exit-code
