name: Run unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - "python-wrapper/src/neo4j_viz/**" # python code + its resources
      - "python-wrapper/pyproject.toml" # dependencies
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    defaults:
      run:
        working-directory: python-wrapper

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - run: pip install ".[dev]"
      - run: pip install ".[pandas]"
      - run: pip install ".[gds]"

      - name: Run tests
        run: pytest tests/ -Werror

  tests-313:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-wrapper
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - run: pip install ".[dev]"
      - run: pip install ".[pandas]"
      # skip gds for now as it is not available for python 3.13

      - name: Run tests
        run: pytest tests/ -Werror
